image: php:8.1

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: magento
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: magento
  MYSQL_PASSWORD: magento

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - vendor/

before_script:
  - apt-get update && apt-get install -y unzip git libzip-dev libicu-dev
  - docker-php-ext-install pdo_mysql intl zip
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer
  - composer install

build:
  stage: build
  script:
    - echo "Building Magento app"
    - composer install

test:
  stage: test
  script:
    - echo "Running tests"
    - php -v
    - php bin/magento setup:di:compile
    - php bin/magento setup:static-content:deploy -f

deploy:
  stage: deploy
  script:
    - echo "Deploying to server"
    # Example: rsync or scp to your hosting server
    # rsync -avz ./ user@yourserver:/var/www/html/
