name: magento
system:
    mode: 'developer'
services:
    php:
        version: '8.2'
        extensions:
            enabled:
                - xsl
                - json
                - redis
    mysql:
        version: '10.6'
        image: 'mariadb'
    redis:
        version: '7.0'
        image: 'redis'
    elasticsearch:
        version: '7.5'
        image: 'elasticsearch'
hooks:
    build: |
        set -e
        php ./vendor/bin/ece-tools run scenario/build/generate.xml
        php ./vendor/bin/ece-tools run scenario/build/transfer.xml
    deploy: 'php ./vendor/bin/ece-tools run scenario/deploy.xml'
    post_deploy: 'php ./vendor/bin/ece-tools run scenario/post-deploy.xml'
mounts:
    var:
        path: 'var'
    app-etc:
        path: 'app/etc'
    pub-media:
        path: 'pub/media'
    pub-static:
        path: 'pub/static'
