name: Magento CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: magento
          MYSQL_USER: magento
          MYSQL_PASSWORD: magento
        ports: [ "3306:3306" ]
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, bcmath, gd, pdo_mysql, soap, xsl, zip
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup Magento (basic)
        run: |
          php bin/magento setup:install \
            --base-url=http://localhost \
            --db-host=127.0.0.1 \
            --db-name=magento \
            --db-user=magento \
            --db-password=magento \
            --admin-firstname=Admin \
            --admin-lastname=User \
            --admin-email=admin@example.com \
            --admin-user=admin \
            --admin-password=Admin123! \
            --language=en_US \
            --currency=USD \
            --timezone=America/Chicago \
            --backend-frontname=admin

      - name: Run Magento compile
        run: php bin/magento setup:di:compile

      - name: Run Magento tests (if any)
        run: vendor/bin/phpunit --testsuite=unit
