name: Magento CI + Deploy
on:
  push:
    branches:
      - main   # run when you push to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Build Magento (Compile DI)
        run: php bin/magento setup:di:compile

  deploy:
    needs: build   # only run after build job is successful
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via FTP
        run: |
          lftp -c "
          set ftp:ssl-allow no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror -R ./ $DEPLOY_PATH
          "
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
